#!/usr/bin/env python3
from mynumbers import Rational

try:
    while True:
        try:
            inp = input("number = ").replace(" ", "")
            x, y = Rational(inp), Rational(float(eval(inp)))
            print("as sum =", x.as_sum())
            print("as frc =", x.as_fraction())
            print("as dec =", x.as_recurring_decimal())
            print("as bin =", x.as_recurring_binary())
            print("as str =", x.as_short_string())
            print("as flt =", y.as_recurring_decimal())
            print()
        except ValueError as e:
            print("\x1b[0;31mERROR:", e, "\x1b[0m", end="\n\n")
except (EOFError, KeyboardInterrupt):
    print("...")
