#!/usr/bin/env python3
from mynumbers import RecurringDecimal, Rational

try:
    while True:
        try:
            inp = input("number = ").replace(" ", "")
            x, y = RecurringDecimal(inp), RecurringDecimal(float(eval(inp)))
            print("as frc =", Rational(x))
            print("as flt =", y)
            print("as dec =", x)
            print()
        except ValueError as e:
            print("\x1b[0;31mERROR:", e, "\x1b[0m", end="\n\n")
except (EOFError, KeyboardInterrupt):
    print("...")
